const mockBriefing = (analysis) => {
  return `
# Executive Summary

ArenaPilot AI has completed the operational assessment successfully.

The current stadium status is **${analysis.overallStatus}** with an overall operational score of **${analysis.overallScore}/100**.

---

# Risk Assessment

Current risk level has been evaluated using the ArenaPilot Rules Engine.

Continue monitoring crowd movement and incident reports.

---

# Crowd Situation

Crowd density has been analyzed across all entry gates.

Recommended crowd redistribution strategies have been generated.

---

# Route Recommendation

Use the safest evacuation and navigation routes generated by the Route Engine.

Security personnel should continuously monitor congestion points.

---

# Accessibility

Accessible entrances and assistance teams should remain available throughout the event.

---

# Transportation

Public transportation should be prioritized to reduce vehicle congestion around the venue.

---

# Sustainability

Maintain recycling stations and encourage digital ticket validation.

---

# Immediate Actions

- Monitor crowd density.
- Monitor medical incidents.
- Monitor security incidents.
- Keep emergency response teams on standby.
- Continue live analysis every few minutes.
`;
};

export default mockBriefing;