import { motion } from "framer-motion";

import {
  FaRobot,
  FaArrowRight,
  FaCheckCircle,
  FaUserShield,
  FaDoorOpen,
  FaAmbulance,
  FaBullhorn,
  FaVideo,
} from "react-icons/fa";

import Card from "../ui/Card";

const defaultActions = [
  {
    title: "Deploy Additional Stewards",
    description:
      "Increase staff presence around Gate B to reduce crowd congestion.",
    priority: "High",
    icon: FaUserShield,
  },
  {
    title: "Open Gate C",
    description:
      "Redirect incoming visitors to reduce waiting time.",
    priority: "Medium",
    icon: FaDoorOpen,
  },
  {
    title: "Dispatch Medical Team",
    description:
      "Nearest response team should inspect Section D immediately.",
    priority: "Critical",
    icon: FaAmbulance,
  },
  {
    title: "Public Announcement",
    description:
      "Notify spectators regarding alternate entry routes.",
    priority: "Medium",
    icon: FaBullhorn,
  },
  {
    title: "Increase CCTV Monitoring",
    description:
      "Enable enhanced surveillance for the affected zone.",
    priority: "Low",
    icon: FaVideo,
  },
];

const priorityColor = {
  Critical: "text-red-400 bg-red-500/10 border-red-500/20",
  High: "text-orange-400 bg-orange-500/10 border-orange-500/20",
  Medium: "text-yellow-400 bg-yellow-500/10 border-yellow-500/20",
  Low: "text-cyan-400 bg-cyan-500/10 border-cyan-500/20",
};

const EmergencyActions = ({ analysis }) => {

  const actions =
    analysis?.recommendations?.length
      ? analysis.recommendations.map((item, index) => ({
          title: item,
          description:
            "Generated by ArenaPilot AI based on current stadium conditions.",
          priority: index === 0 ? "High" : "Medium",
          icon: FaRobot,
        }))
      : defaultActions;

  return (
    <Card>

      {/* Header */}

      <div className="mb-8 flex items-center justify-between">

        <div>

          <h2 className="font-heading text-2xl font-bold text-white">
            AI Recommended Actions
          </h2>

          <p className="mt-2 text-slate-400">
            Operational recommendations generated by ArenaPilot AI.
          </p>

        </div>

        <div className="flex items-center gap-2 rounded-xl border border-cyan-500/20 bg-cyan-500/10 px-4 py-2">

          <FaRobot className="text-cyan-400" />

          <span className="text-cyan-300 font-medium">
            AI Active
          </span>

        </div>

      </div>

      {/* Cards */}

      <div className="grid gap-5 lg:grid-cols-2">

        {actions.map((action, index) => {

          const Icon = action.icon;

          return (

            <motion.div
              key={index}
              initial={{
                opacity: 0,
                y: 20,
              }}
              animate={{
                opacity: 1,
                y: 0,
              }}
              transition={{
                delay: index * 0.08,
              }}
              className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6 transition hover:border-cyan-500/30"
            >

              <div className="flex items-start justify-between">

                <div className="flex gap-4">

                  <div className="rounded-xl bg-cyan-500/10 p-4">

                    <Icon className="text-2xl text-cyan-400" />

                  </div>

                  <div>

                    <h3 className="font-heading text-lg font-semibold text-white">
                      {action.title}
                    </h3>

                    <p className="mt-2 text-sm leading-6 text-slate-400">
                      {action.description}
                    </p>

                  </div>

                </div>

                <span
                  className={`rounded-full border px-3 py-1 text-xs font-semibold ${
                    priorityColor[action.priority]
                  }`}
                >
                  {action.priority}
                </span>

              </div>

              <div className="mt-6 flex items-center justify-between border-t border-slate-800 pt-4">

                <div className="flex items-center gap-2 text-sm text-emerald-400">

                  <FaCheckCircle />

                  Ready to Execute

                </div>

                <button
                  className="flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950 transition hover:bg-cyan-400"
                >
                  Execute

                  <FaArrowRight />
                </button>

              </div>

            </motion.div>

          );

        })}

      </div>

    </Card>
  );
};

export default EmergencyActions;