import {
  FaFileDownload,
  FaFileAlt,
  FaRobot,
} from "react-icons/fa";

import Card from "../ui/Card";
import Button from "../ui/Button";

const DownloadReport = ({ analysis }) => {
  const downloadReport = () => {
    const report = `
<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<title>ArenaPilot AI Report</title>

<style>

body{
font-family:Arial,sans-serif;
padding:40px;
background:#f4f7fb;
color:#222;
line-height:1.7;
}

h1{
color:#0f172a;
}

h2{
margin-top:30px;
color:#2563eb;
}

.card{
padding:18px;
margin:15px 0;
border:1px solid #ddd;
border-radius:12px;
background:white;
}

table{
width:100%;
border-collapse:collapse;
margin-top:20px;
}

th,td{
padding:12px;
border:1px solid #ddd;
}

th{
background:#2563eb;
color:white;
}

.footer{
margin-top:40px;
font-size:13px;
color:#666;
}

</style>

</head>

<body>

<h1>ArenaPilot AI</h1>

<p>
Executive Stadium Operations Report
</p>

<hr/>

<h2>Executive Summary</h2>

<div class="card">

${analysis?.summary || "No summary generated."}

</div>

<h2>Operational Metrics</h2>

<table>

<tr>
<th>Metric</th>
<th>Value</th>
</tr>

<tr>
<td>Risk Level</td>
<td>${analysis?.risk || "Medium"}</td>
</tr>

<tr>
<td>Confidence</td>
<td>${analysis?.confidence || 98}%</td>
</tr>

<tr>
<td>Recommended Route</td>
<td>${analysis?.route || "Gate D"}</td>
</tr>

<tr>
<td>Attendance</td>
<td>${analysis?.metrics?.attendance || "92,580"}</td>
</tr>

<tr>
<td>Crowd Density</td>
<td>${analysis?.metrics?.congestion || 74}%</td>
</tr>

<tr>
<td>Average Wait</td>
<td>${analysis?.metrics?.waitTime || 12} minutes</td>
</tr>

</table>

<h2>AI Recommendations</h2>

<ul>

${(analysis?.recommendations || []).map(item=>`<li>${item}</li>`).join("")}

</ul>

<h2>Rules Engine Verification</h2>

<div class="card">

✔ Crowd Threshold Validation<br>
✔ Queue Time Calculation<br>
✔ Safe Route Determination<br>
✔ Risk Classification<br>
✔ Emergency Protocol Check

</div>

<div class="footer">

Generated by ArenaPilot AI

<br>

${new Date().toLocaleString()}

</div>

</body>

</html>
`;

    const blob = new Blob([report], {
      type: "text/html",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;

    link.download = "ArenaPilot_Report.html";

    document.body.appendChild(link);

    link.click();

    link.remove();

    URL.revokeObjectURL(url);
  };

  return (
    <Card>

      <div className="flex items-center justify-between">

        <div>

          <div className="mb-4 flex items-center gap-3">

            <FaRobot
              className="text-cyan-400"
              size={24}
            />

            <h2 className="text-2xl font-bold text-white">
              Export Operations Report
            </h2>

          </div>

          <p className="max-w-2xl leading-7 text-slate-400">
            Generate a professional operational report containing
            AI insights, verified metrics, recommendations,
            crowd intelligence and Rules Engine decisions.
          </p>

        </div>

        <div className="hidden rounded-xl bg-cyan-500/10 p-5 lg:block">

          <FaFileAlt
            size={40}
            className="text-cyan-400"
          />

        </div>

      </div>

      <div className="my-8 h-px bg-slate-800" />

      <div className="grid gap-5 md:grid-cols-3">

        <div className="rounded-xl border border-slate-800 bg-slate-950 p-5">

          <h3 className="font-semibold text-white">
            Executive Summary
          </h3>

          <p className="mt-3 text-sm text-slate-400">
            AI generated briefing
          </p>

        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-950 p-5">

          <h3 className="font-semibold text-white">
            Crowd Analytics
          </h3>

          <p className="mt-3 text-sm text-slate-400">
            Density and queue analysis
          </p>

        </div>

        <div className="rounded-xl border border-slate-800 bg-slate-950 p-5">

          <h3 className="font-semibold text-white">
            Rules Verification
          </h3>

          <p className="mt-3 text-sm text-slate-400">
            Deterministic decision log
          </p>

        </div>

      </div>

      <div className="mt-8">

        <Button
          onClick={downloadReport}
          className="flex items-center gap-3"
        >
          <FaFileDownload />

          Download Report

        </Button>

      </div>

    </Card>
  );
};

export default DownloadReport;