import {
  FaUsers,
  FaHeartbeat,
  FaShieldAlt,
  FaCloudSun,
  FaBroadcastTower,
  FaBus,
} from "react-icons/fa";

import Card from "../ui/Card";

const IncidentPanel = ({ analysis }) => {
  const crowd = analysis?.crowd || {};
  const risk = analysis?.risk || {};
  const transport = analysis?.transport || {};

  const congestion =
    crowd.score ?? 74;

  const medicalRisk =
    risk.medicalRisk ?? "Low";

  const securityRisk =
    risk.securityRisk ?? "Low";

  const weatherRisk =
    risk.weatherRisk ?? "Clear";

  const traffic =
    transport.trafficLevel ?? "Moderate";

  const incidents = [
    {
      title: "Crowd Congestion",
      value: `${congestion}%`,
      status:
        congestion >= 85
          ? "Critical"
          : congestion >= 65
          ? "High"
          : "Normal",
      description:
        "Current crowd density across monitored gates.",
      icon: FaUsers,
    },

    {
      title: "Medical Readiness",
      value: medicalRisk,
      status:
        medicalRisk === "High"
          ? "Attention"
          : "Ready",
      description:
        "Medical response capability.",
      icon: FaHeartbeat,
    },

    {
      title: "Security",
      value: securityRisk,
      status:
        securityRisk === "High"
          ? "Attention"
          : "Excellent",
      description:
        "Current security assessment.",
      icon: FaShieldAlt,
    },

    {
      title: "Weather",
      value: weatherRisk,
      status: weatherRisk,
      description:
        "Weather impact on operations.",
      icon: FaCloudSun,
    },

    {
      title: "Communications",
      value: "Online",
      status: "Stable",
      description:
        "Command center and radio systems operational.",
      icon: FaBroadcastTower,
    },

    {
      title: "Transport",
      value: traffic,
      status:
        traffic === "Heavy"
          ? "Attention"
          : "Normal",
      description:
        "Traffic and transport network status.",
      icon: FaBus,
    },
  ];

  const getStatusStyle = (status) => {
    switch (status) {
      case "Critical":
        return {
          badge:
            "bg-red-500/10 text-red-400 border-red-500/20",
          icon: "text-red-400",
        };

      case "High":
      case "Attention":
      case "Storm":
      case "Heavy":
        return {
          badge:
            "bg-yellow-500/10 text-yellow-300 border-yellow-500/20",
          icon: "text-yellow-400",
        };

      default:
        return {
          badge:
            "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
          icon: "text-emerald-400",
        };
    }
  };

  return (
    <Card>

      <div className="mb-8">

        <h2 className="text-2xl font-bold text-white">
          Incident Assessment
        </h2>

        <p className="mt-2 text-slate-400">
          Real-time operational status generated by ArenaPilot AI.
        </p>

      </div>

      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">

        {incidents.map((item) => {
          const style = getStatusStyle(item.status);
          const Icon = item.icon;

          return (
            <div
              key={item.title}
              className="rounded-2xl border border-slate-800 bg-slate-950 p-5 transition hover:border-cyan-500/30"
            >
              <div className="mb-5 flex items-center justify-between">

                <div className="rounded-xl bg-slate-800 p-3">
                  <Icon
                    size={22}
                    className={style.icon}
                  />
                </div>

                <span
                  className={`rounded-full border px-3 py-1 text-xs font-semibold ${style.badge}`}
                >
                  {item.status}
                </span>

              </div>

              <h3 className="text-lg font-semibold text-white">
                {item.title}
              </h3>

              <div className="mt-3 text-3xl font-bold text-cyan-400">
                {item.value}
              </div>

              <p className="mt-4 text-sm leading-6 text-slate-400">
                {item.description}
              </p>

            </div>
          );
        })}

      </div>

      <div className="mt-8 rounded-2xl border border-cyan-500/20 bg-cyan-500/10 p-5">

        <h3 className="text-lg font-semibold text-cyan-400">
          AI Operational Assessment
        </h3>

        <p className="mt-3 leading-7 text-slate-300">
          {risk.executiveSummary ||
            "Operations remain stable. ArenaPilot AI recommends continuous monitoring of crowd density, transport flow, and emergency resources while maintaining normal operational readiness."}
        </p>

      </div>

    </Card>
  );
};

export default IncidentPanel;