import {
  FaRobot,
  FaBrain,
  FaArrowTrendUp,
  FaTriangleExclamation,
  FaCircleCheck,
  FaClock,
} from "react-icons/fa6";

import Card from "../ui/Card";

const PredictionPanel = ({ analysis }) => {
  const risk = analysis?.risk || "Medium";
  const confidence = analysis?.confidence || 98;

  const recommendations =
    analysis?.recommendations || [
      "Redirect spectators toward Gate D.",
      "Deploy additional crowd management volunteers.",
      "Open secondary security checkpoint.",
      "Increase public announcement frequency.",
    ];

  const riskColor = {
    Low: "text-emerald-400",
    Medium: "text-yellow-400",
    High: "text-orange-400",
    Critical: "text-red-400",
  };

  const riskBg = {
    Low: "bg-emerald-500/10 border-emerald-500/20",
    Medium: "bg-yellow-500/10 border-yellow-500/20",
    High: "bg-orange-500/10 border-orange-500/20",
    Critical: "bg-red-500/10 border-red-500/20",
  };

  return (
    <Card className="space-y-6">

      {/* Header */}

      <div className="flex items-center justify-between">

        <div>

          <h2 className="text-xl font-bold text-white">
            AI Prediction Center
          </h2>

          <p className="mt-1 text-sm text-slate-400">
            Generated by ArenaPilot AI
          </p>

        </div>

        <div className="rounded-xl bg-cyan-500/10 p-4">
          <FaRobot
            className="text-cyan-400"
            size={28}
          />
        </div>

      </div>

      {/* Confidence */}

      <div className="grid grid-cols-2 gap-4">

        <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/10 p-5">

          <div className="flex items-center gap-3">

            <FaBrain className="text-cyan-400" />

            <span className="text-sm text-slate-400">
              Confidence
            </span>

          </div>

          <h2 className="mt-3 text-3xl font-bold text-cyan-400">
            {confidence}%
          </h2>

        </div>

        <div className={`rounded-xl border p-5 ${riskBg[risk]}`}>

          <div className="flex items-center gap-3">

            <FaTriangleExclamation className={riskColor[risk]} />

            <span className="text-sm text-slate-400">
              Risk
            </span>

          </div>

          <h2 className={`mt-3 text-3xl font-bold ${riskColor[risk]}`}>
            {risk}
          </h2>

        </div>

      </div>

      {/* Forecast */}

      <div className="rounded-xl border border-slate-800 bg-slate-950 p-5">

        <div className="mb-5 flex items-center gap-3">

          <FaArrowTrendUp className="text-purple-400" />

          <h3 className="font-semibold text-white">
            Forecast
          </h3>

        </div>

        <div className="space-y-4">

          <div className="flex items-center justify-between">

            <span className="text-slate-400">
              Crowd Spike
            </span>

            <span className="font-semibold text-white">
              12 Minutes
            </span>

          </div>

          <div className="flex items-center justify-between">

            <span className="text-slate-400">
              Peak Occupancy
            </span>

            <span className="font-semibold text-red-400">
              92%
            </span>

          </div>

          <div className="flex items-center justify-between">

            <span className="text-slate-400">
              Expected Recovery
            </span>

            <span className="font-semibold text-emerald-400">
              18 Minutes
            </span>

          </div>

        </div>

      </div>

      {/* Recommendations */}

      <div>

        <div className="mb-4 flex items-center gap-3">

          <FaCircleCheck className="text-emerald-400" />

          <h3 className="font-semibold text-white">
            Recommended Actions
          </h3>

        </div>

        <div className="space-y-3">

          {recommendations.map((item, index) => (
            <div
              key={index}
              className="flex items-start gap-3 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4"
            >
              <FaCircleCheck className="mt-1 text-emerald-400" />

              <span className="text-sm leading-6 text-slate-300">
                {item}
              </span>

            </div>
          ))}

        </div>

      </div>

      {/* Next Update */}

      <div className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950 p-4">

        <div className="flex items-center gap-3">

          <FaClock className="text-cyan-400" />

          <span className="text-slate-400">
            Next AI Refresh
          </span>

        </div>

        <span className="font-semibold text-cyan-400">
          30 sec
        </span>

      </div>

    </Card>
  );
};

export default PredictionPanel;