import {
  FaRobot,
  FaBrain,
  FaArrowTrendUp,
  FaTriangleExclamation,
  FaCircleCheck,
  FaClock,
} from "react-icons/fa6";

import Card from "../ui/Card";

const PredictionPanel = ({ analysis }) => {
  const risk = analysis?.risk ?? "Moderate";

  const confidence = analysis?.crowd?.prediction?.confidence ?? 97;

  const prediction = analysis?.crowd?.prediction ?? null;

  const recommendations = analysis?.recommendations ??
    analysis?.riskAnalysis?.recommendations ??
    [];

  const trend = analysis?.crowd?.hourlyTrend ?? [];


  const peak =
    trend.length > 0
      ? Math.max(...trend.map((item) => item.density))
      : 82;

  const riskColor = {
    Low: "text-emerald-400",
    Moderate: "text-yellow-400",
    High: "text-orange-400",
    Critical: "text-red-400",
  };

  const riskBg = {
    Low: "bg-emerald-500/10 border-emerald-500/20",
    Moderate:
      "bg-yellow-500/10 border-yellow-500/20",
    High: "bg-orange-500/10 border-orange-500/20",
    Critical: "bg-red-500/10 border-red-500/20",
  };

  return (
    <Card className="space-y-6">

      {/* Header */}

      <div className="flex items-center justify-between">

        <div>
          <h2 className="text-xl font-bold text-white">
            AI Prediction Center
          </h2>

          <p className="mt-1 text-sm text-slate-400">
            Generated by ArenaPilot AI
          </p>
        </div>

        <div className="rounded-xl bg-cyan-500/10 p-4">
          <FaRobot
            className="text-cyan-400"
            size={28}
          />
        </div>

      </div>

      {/* Top Cards */}

      <div className="grid grid-cols-2 gap-4">

        <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/10 p-5">

          <div className="flex items-center gap-3">
            <FaBrain className="text-cyan-400" />

            <span className="text-sm text-slate-400">
              Confidence
            </span>
          </div>

          <h2 className="mt-3 text-3xl font-bold text-cyan-400">
            {confidence}%
          </h2>

        </div>

        <div
          className={`rounded-xl border p-5 ${
            riskBg[risk]
          }`}
        >

          <div className="flex items-center gap-3">
            <FaTriangleExclamation
              className={riskColor[risk]}
            />

            <span className="text-sm text-slate-400">
              Risk
            </span>
          </div>

          <h2
            className={`mt-3 text-3xl font-bold ${
              riskColor[risk]
            }`}
          >
            {risk}
          </h2>

        </div>

      </div>

      {/* Forecast */}

      <div className="rounded-xl border border-slate-800 bg-slate-950 p-5">

        <div className="mb-5 flex items-center gap-3">

          <FaArrowTrendUp className="text-purple-400" />

          <h3 className="font-semibold text-white">
            Forecast
          </h3>

        </div>

        <div className="space-y-4">

          <div className="flex items-center justify-between">

            <span className="text-slate-400">
              Next 30 Minutes
            </span>

            <span className="font-semibold text-white">
              {prediction?.next30Minutes ||
                "Stable"}
            </span>

          </div>

          <div className="flex items-center justify-between">

            <span className="text-slate-400">
              Peak Density
            </span>

            <span className="font-semibold text-red-400">
              {peak}%
            </span>

          </div>

          <div className="flex items-center justify-between">

            <span className="text-slate-400">
              Prediction Confidence
            </span>

            <span className="font-semibold text-emerald-400">
              {prediction?.confidence || 97}%
            </span>

          </div>

        </div>

      </div>

      {/* Recommendations */}

      <div>

        <div className="mb-4 flex items-center gap-3">

          <FaCircleCheck className="text-emerald-400" />

          <h3 className="font-semibold text-white">
            Recommended Actions
          </h3>

        </div>

        <div className="space-y-3">

          {recommendations.map((item, index) => (
            <div
              key={index}
              className="flex items-start gap-3 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4"
            >

              <FaCircleCheck className="mt-1 text-emerald-400" />

              <span className="text-sm leading-6 text-slate-300">
                {item}
              </span>

            </div>
          ))}

        </div>

      </div>

      {/* Footer */}

      <div className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950 p-4">

        <div className="flex items-center gap-3">

          <FaClock className="text-cyan-400" />

          <span className="text-slate-400">
            Next AI Refresh
          </span>

        </div>

        <span className="font-semibold text-cyan-400">
          30 sec
        </span>

      </div>

    </Card>
  );
};

export default PredictionPanel;